### ISSUE TITLE
Add support for Group Messages

### ISSUE THREAD

**Issue by aarring** [Brismuth-Apps-LLC/bulk-texter-lite#143]
I am a virtual teacher and I love to use Bulk Texter as a way to reach all of my students with similar updates and messages as well as reach out to smaller groups of students individually about assignments, work, etc.

One thing I would love to be able to do is send the same group message to students and their parent.  For example if a student has not submitted work in 7 days, being able to text the student and parent with a proactive message as a group, but that retains the confidentiality of the student by not creating a large group message with lots of students.

This would save me lots of time from collecting numbers and creating individual group messages and allow me to better target those students who require more accountability from their parents.

**Comment by jennyrette** [comment]
Yes! I agree, I was searching to see if this was an option.  Would love to be able to do that! Thank you for asking about it.

**Comment by brismuth** [comment]
People who would like this issue prioritized can fund it here:
https://issuehunt.io/r/brismuth/google-voice-bulk-texter/issues/143

**Comment by brismuth** [comment]
Hey folks - I have an exciting announcement!

I just launched Bulk Texter Pro over at https://www.bulktexterpro.com/ - it supports CSV upload with multiple columns, as well as scheduling messages in advance and message previewing - it's pretty slick. 
Group messages are not currently supported, but it's on the roadmap: https://www.bulktexterpro.com/docs/features/

I'd love if you could check it out and drop any feedback you have here.
