### ISSUE TITLE
Add support for sending images

### ISSUE THREAD

**Issue by Rappy805** [Brismuth-Apps-LLC/bulk-texter-lite#144]
Hi there, firstly... super pleased with the bulk texting option. I have utilized remind and other apps in the past and I love that this works with voice to send the BCCs. Bravo there. I would love to see the ability to add bitmoji, emoji, GIF, and images or google slides to the messages. I know nothing about coding so if that is absurd please disregard. I just send lots of images in bulk to my students and would love to have that capability moving forward and I know many of my colleagues would appreciate the chance to utilize your code for that purpose as well. 
~Mrs. Rapoza

**Comment by volkankaban** [comment]
Thanks for all updates.

**Comment by SonJ1** [comment]
> Hi there, firstly... super pleased with the bulk texting option. I have utilized remind and other apps in the past and I love that this works with voice to send the BCCs. Bravo there. I would love to see the ability to add bitmoji, emoji, GIF, and images or google slides to the messages. I know nothing about coding so if that is absurd please disregard. I just send lots of images in bulk to my students and would love to have that capability moving forward and I know many of my colleagues would appreciate the chance to utilize your code for that purpose as well.
> ~Mrs. Rapoza

I DESPERATELY need this for my business! PLEASE PLEASE! ASAP! :))

**Comment by brismuth** [comment]
People who would like this issue prioritized can fund it here:
https://issuehunt.io/r/brismuth/google-voice-bulk-texter/issues/144

**Comment by Rappy805** [comment]
Hey there! What is the total amount you need to fund the project please?

**Comment by SonJ1** [comment]
Total amount?

**Comment by brismuth** [comment]
Hey folks, thanks for the interest in this feature. I've been looking into feasibility, and here's the options I see:
1. Wait until Google adds support for copy/pasting images into Google Voice, which will make this easier to add (not currently supported by Google, see these links: [1](https://support.google.com/voice/thread/11989349/i-can-t-paste-screenshots-anymore-into-gv-messaging-used-to-work-has-something-changed?hl=en), [2](https://www.reddit.com/r/Googlevoice/comments/kbmw1a/possible_to_copypaste_images_into_google/))
2. Tie into Google Voice's current image upload flow. Chrome Extensions don't have access to the local file picker (the "Upload photos" tab), so the only real option here would be to integrate with Google Photos. And I'm guessing that for that to work reliably, it would have to be a photo you've recently uploaded to Google Photos, and even then I think it would be unreliable and confusing for general users.

At this point I'm inclined to wait for option 1 to be viable.

**Comment by brismuth** [comment]
Hey folks - I have an exciting announcement!

I just launched Bulk Texter Pro over at https://www.bulktexterpro.com/ - it supports CSV upload with multiple columns, as well as scheduling messages in advance and message previewing - it's pretty slick. Image sending is not currently supported, but I dug in some more and have some ideas, and it's on the roadmap: https://www.bulktexterpro.com/docs/features/

I'd love if you could check it out and drop any feedback you have here.
