### ISSUE TITLE
Option to Ignore Sent Confirmation 

### ISSUE THREAD

**Issue by CasaDeChavez** [Brismuth-Apps-LLC/bulk-texter-lite#170]
Add the option the users check to allow the program to ignore wait for sent confirmation before sending the next message.

This will solve the issue of bulk texter loop over the first message (because it did not receive sent confirmation from Google Voice, though it already sent successfully) thinking it’s continuously failing until message pops up saying it failed (on the first one) because there’s no sent confirmation.

Add a confirmation window when users check this option to ignore so they will know what it means and can use it at their own risk.

Force the send delay to be 5 or 10 seconds (or longer to be more secure) after checking this option so users can be fairly certain the previous message has been sent before bulk texter gets to the next one.

**Comment by CasaDeChavez** [comment]
Details:

(Possible cause: confirmation is delayed may due to message being too long)

It seems there are quite a few people having the issue of not sending past first number.  In this situation the delay between texts will not help.


What happens here is that after the first number has been successfully sent, the bulk texter does not receive the sent confirmation from Google Voice, so bulk texter believes it failed the first message, and it tries again.

And again it does not get a confirmation, so it tries again and again until it eventually says that it failed to send the first number/message because it did not get the confirmation even once with multiple tries, though it was sent first time.


Delay between sends will not work here since it’s a confirmation check issue.  So I set the delay to 5 minutes.  But the fact remains that the bulk texter still cannot get the first sent confirmation after it was successfully sent.  So, sure, it will wait 5 min before sending the 2nd message/text 2nd number, but it believes that it has failed even the first number, so within 4 seconds it tries to send the first number again, and again, until it says it cannot continue with the rest 100 numbers since it could not even get the first one delivered.  The program never got to the delay time part of the macro.



So the issue there lies in Google Voice not letting bulk texter see the sent confirmation, though I/a user can clearly see that the message is sent.


This does not seem to be Google Voice seeing the message as spam.  I tried to send those messages myself, individually once every 10 seconds, and I was able to send the entire bulk (over a dozen) until the testing list was finished.


So bulker texter sends the first message perfectly, and then it thinks it did not, and it gets stuck there.




Solution 1:

One simple solution would be skip the sent confirmation (from Voice), and just send the (next) texts every 5 minutes like I asked.



Of course we should not skip sent confirmation so lightly, so we can simply add the option, for the user to implement when issues like this occur.  Add a confirmation window/message before disable this check to make this option safer if need be.



I have tried 20 times bulk sending with the long message, and all 20 times bulk texter has sent the first phone number perfectly when it notified me that it has unfortunately failed the first text message after quite a few tries.  So I know that even without confirmation it would have sent those messages successfully, Easily (every a certain long interval).


We are the busy management part of the apartment business, and we may need to send 100+ messages to tenants, between having a sent confirmation check in bulk texter and not send a single message, or (an option to) not having a sent confirm check and send these 100+ messages automatically for us, I choose the 2nd one any day.



I do all the programming for this apartment business, and I have met similar issues and that’s how I was able to deduce it was the confirmation check miscommunication.


To ensure the accuracy of my program, I added confirmation check/monitor every step, but sometimes the program just cannot see the confirmation one way or another (because the user did something too unique, which is too often), I got too tired, so I added the option everywhere for the user to ignore the confirmation check by the program, and it really has never had any problem without many of these checks.



When the user ticks to ignore confirmation checks, just show a popup message to confirm or a message below to warn the user.

What I do in my program (changing the phrases to match bulk texter):

“You have checked to the disable the sent confirmation monitor(check), Bulk Texter will now send the messages on the list without confirming if the previous message has been sent.  Are you sure you want to check this option?”

You can also add: “I understand and I will use bulk texter without sent confirmation check at my own risk.” or something similar, if you’d like.


For your texter macro, you might want to add in above message: “Note: to check this option, the delay between texts must be at least 5 (or 10 or more) seconds.” and just auto check the delay to 5-10+ sec after user okays to ignore sent confirmation, since without confirmation check, it’s possible that the bulk texter can send the next one, too fast, without previous text having the time to complete.

**Comment by brismuth** [comment]
Thanks for the suggestion/feature request - I've added the enhancement label.

**Comment by CasaDeChavez** [comment]
Thanks!

**Comment by brismuth** [comment]
Hey folks - I have an exciting announcement!

I just launched Bulk Texter Pro over at https://www.bulktexterpro.com/ - it supports CSV upload with multiple columns, as well as scheduling messages in advance and message previewing - it's pretty slick. It also basically supports the functionality requested here, because instead of halting when a message fails to send, it will store that status for viewing later and move on to the next message.

I'd love if you could check it out and drop any feedback you have here.

**Comment by brismuth** [comment]
Whoa, @CasaDeChavez I never saw your edits in here, they provide a ton of detail. This is really interesting...

I'm going to think about this, and may remove the confirmSent step altogether, honestly.

**Comment by brismuth** [comment]
@CasaDeChavez in the latest release (v2.1.0), I ended up going ahead and adjusting the send delays and removing confirmSent altogether.

Thanks again for the feedback and level of detail here!
