### ISSUE TITLE
Error: "confirmSent" failed.

### ISSUE THREAD

**Issue by joebarnes1983** [Brismuth-Apps-LLC/bulk-texter-lite#194]
Getting this error after every number. Have removed and reinstalled, and cleared all cache/cookies.

Bulk SMS - Google Voice bulk texter v2.0.1: Text failed. You can find support resources by opening the Google Voice Bulk Texter popup and clicking "Get Help" at the bottom. Error: "confirmSent" failed. When you click "ok" the page will refresh.

Started happening over the last week. Have been using the extension with no issue for a couple years.

**Comment by brismuth** [comment]
See https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed.

Are the messages sending correctly, and the extension is failing to detect that, or are they actually failing to send?

**Comment by joebarnes1983** [comment]
> See https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed.
> 
> Are the messages sending correctly, and the extension is failing to detect that, or are they actually failing to send?

The first message will send properly. Then it repeatedly tries to send it again before the error message mentioned above appear. Then I have to refresh, delete the first number on the list, and it repeats the same process of sending the first message only before giving me the error message.

**Comment by brismuth** [comment]
If the message is definitely sending successfully, it's possible that Google is changing the code for the frontend of Google Voice, and that they're just rolling it out to a limited group of people right now. That could be what's breaking it for you - we've seen that type of thing happen before.

I've been experimenting with some code changes that would allow you to export the Google Voice page HTML to share with me via email for troubleshooting, in the event of an error like this one. Would you want to try that? If so, go ahead and email me at the email address on my profile here: https://github.com/brismuth and I'll send you instructions.

**Comment by brismuth** [comment]
Per #204 this is happening on version v2.0.5 of the extension as well.

**Comment by dsbsnag** [comment]
Apologies.  This is my exact issue and I inadvertanly created a new issue

**Comment by dsbsnag** [comment]
I closed my duplicate issue; but, I think it was number 205 or 215
