### ISSUE TITLE
Extension is looping on a single number and failing WITHOUT an error message

### ISSUE THREAD

**Issue by Jaccooley** [Brismuth-Apps-LLC/bulk-texter-lite#195]
**Describe the bug**
keeps looping and texting the first number on the list 

**URL**
The URL you were on when the problem occurred. 
https://voice.google.com/u/0/messages?itemId=draft-D15B501B-F25B-47DD-8A3C-0EE2CB0C8811 

**Expected behavior**
Send a bulk text to the provided numbers in list 

**Screenshots**

**Additional context**

**Comment by brismuth** [comment]
@Jaccooley are you sure you let it retry long enough? It takes a while but after 5 attempts to send a message, it should always output an error.

**Comment by jbunch7** [comment]
<img width="649" alt="Screen Shot 2022-11-20 at 2 40 47 PM" src="https://user-images.githubusercontent.com/118226703/202925880-64285f0d-c923-49dc-9cf4-c1e875832118.png">

**Comment by jbunch7** [comment]
The problem might just be in the phone number it was trying to text. I skipped over the number where it got stuck and its working again

**Comment by brismuth** [comment]
I'm glad you got this figured out for your case @jbunch7!

@Jaccooley I believe I tracked down the source of the looping without error and resolved it in the most recent version of Bulk Texter Lite. Let me know if this is still happening for you on v2.0.10.
