### ISSUE TITLE
"confirmChatSwitched" failed error on even single send with texter

### ISSUE THREAD

**Issue by Cpt-Jera** [Brismuth-Apps-LLC/bulk-texter-lite#201]
Multiple numbers failed with error.  Sending to only 10, same error.  Sending to a single number, ditto.
![image](https://user-images.githubusercontent.com/105049400/193926425-61298522-4263-43ed-92dc-c966add1b16e.png)

Finding no support or reference for this error.

**Comment by brismuth** [comment]
Please update to the latest version of the extension following the instructions in the readme - this issue has already been fixed.

**Comment by jl-montes** [comment]
I have version 2.0.1 and also get the confirmChatSwitched error message

**Comment by brismuth** [comment]
@sandoval484 if you're using FireFox then you'll already be on the latest version automatically, and that would mean that there are new changes to Google Voice that are breaking the extension.

I just tested it on my side and it's still working for my Google Account, so I can't fix it on my own. 

However, if you email me at support@bulktexterpro.com, I can send you some additional troubleshooting steps.

**Comment by brismuth** [comment]
@Cpt-Jera @jl-montes - 
@sandoval484 reported this fixed in the latest version - 2.0.10 - give it a try and let me know!

**Comment by sandoval484** [comment]
As a daily user of your bulk text on gvoice. I noticed that some text dont get to phone bit some do. Usually 1 out of 30 wont get certain text
Not sure if its something on there end or mine or gvoice. Seems like gvoice isnt working as great as it did 2years ago.
Do you know anything about the service being recently bad? 
Do you do bulk text for anything else besides gvoice? 



Sent from Yahoo Mail for iPhone


On Friday, November 18, 2022, 1:35 PM, Brian Smith ***@***.***> wrote:




@sandoval484 if you're using FireFox then you'll already be on the latest version automatically, and that would mean that there are new changes to Google Voice that are breaking the extension.

I just tested it on my side and it's still working for my Google Account, so I can't fix it on my own.

However, if you email me at ***@***.***, I can send you some additional troubleshooting steps.

**Comment by brismuth** [comment]
I haven't heard anything about recent degradations to Google Voice's service.

Bulk Texter Pro supports Google Voice and iMessage, and I'm anticipating adding support for Android and TextNow by the end of the year. You can see a breakdown of the differences between Bulk Texter Lite and Bulk Texter Pro here:
https://www.bulktexterpro.com/docs/features/
