### ISSUE TITLE
Fill Number Input Error

### ISSUE THREAD

**Issue by orrills** [Brismuth-Apps-LLC/bulk-texter-lite#203]
Sending bulk txt with Google Voice bulk Text. I get fill number input error. I'm using Chrome and it was working when I first downloaded it and now I get this error everytime.

**Comment by brismuth** [comment]
Can you include a screenshot of the error message?

**Comment by orrills** [comment]
Thank you,
Danielle Meta
Office Manager
*Orrill's Auction est. 1928*
818-951-7653
orrillsauction.com

**Comment by brismuth** [comment]
By the way, if you sent a screenshot, it didn't come through - I think you'd need to open this thread on Github and post it there.

Is the issue still happening for you?
