### ISSUE TITLE
not working - not sending msgs

### ISSUE THREAD

**Issue by Arnoldmatias1** [Brismuth-Apps-LLC/bulk-texter-lite#208]
![image](https://user-images.githubusercontent.com/119699850/205367522-aad51ef4-c270-4d44-9654-9fe83696a2fe.png)

Text failed - Error : confirmSent failed

**Comment by Arnoldmatias1** [comment]
Please let me know how to fix this - thank you!!

**Comment by brismuth** [comment]
Hi, thanks for reaching out.

It looks like you're on the old version of the extension - can you update to the newest version and see if you're having the issue there too?

Here are the instructions for updating it:https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/blob/main/README.md#update-it
