### ISSUE TITLE
wont send all in the address box , just send a few and stops

### ISSUE THREAD

**Issue by kayhouser** [Brismuth-Apps-LLC/bulk-texter-lite#209]
**Describe the bug**

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by brismuth** [comment]
Can you add a screenshot of the error message that you're getting? Or are you not getting an error message?

**Comment by kayhouser** [comment]
Not getting an error message.  I put in about 35 numbers and it skips some
then stops sending.

**Comment by brismuth** [comment]
Can you share which version of the extension you are using? That should be at the bottom right of the popup interface.

If it's not 2.0.10, you should update following these instructions:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite#update-it

**Comment by kayhouser** [comment]
It is version 2.0.10. Is there a limit on how many email addresses to send
at a time? Could that be an issue if I sent about 40-45 at a time?

**Comment by brismuth** [comment]
Not within the extension itself, but Google Voice does limit the speed of sending. They have algorithms to detect spam etc and will temporarily block sending if those are triggered. 

You can read more on the support page here:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/blob/main/support.md#account-suspension--error-confirmsent-failed

**Comment by kayhouser** [comment]
What format is needed for numbers? Is area code in brackets and a hyphen
needed such as (123)456-7890 or can it be just 1234567890
Thank you

**Comment by brismuth** [comment]
Either way should work just fine.

**Comment by brismuth** [comment]
Are you still having issues with this?

**Comment by kayhouser** [comment]
It will let me send 40 then stops  a few into the next 40. Have to wait 24
hrs before it will let me send again.

**Comment by DaG2022** [comment]
![image](https://user-images.githubusercontent.com/119456709/207921111-0a3d257f-1968-4131-a91c-35bc2f266399.png)
What error is this?? Is that we facing the same problem?

**Comment by kayhouser** [comment]
All all get is the error in the first sentence of the above screen shot ,
by the red circle 🔴

**Comment by brismuth** [comment]
See the support page I linked above, this is how Bulk Texter Lite handles it when Google is temporarily blocking message sending on your account:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/blob/main/support.md#account-suspension--error-confirmsent-failed
