### ISSUE TITLE
Why this happen?

### ISSUE THREAD

**Issue by DaG2022** [Brismuth-Apps-LLC/bulk-texter-lite#210]
**Describe the bug**

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**
If applicable, add s
![Snipaste_2022-12-14_13-12-08](https://user-images.githubusercontent.com/119456709/207673888-42295376-72e4-4dc2-9284-cf0745891300.PNG)
creenshots to help explain your problem.

**Additional context**

**Comment by brismuth** [comment]
See the support page:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/blob/main/support.md#account-suspension--error-confirmsent-failed

**Comment by DaG2022** [comment]
![image](https://user-images.githubusercontent.com/119456709/207921696-c8ae03cc-4ebd-48fe-b9e3-17648bae10c4.png)
Hi, is that my google voice issue or any wrong error about the extension? I'm using the lastest version now

**Comment by brismuth** [comment]
See the support page I linked above, this is how Bulk Texter Lite handles it when Google is temporarily blocking message sending on your account:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/blob/main/support.md#account-suspension--error-confirmsent-failed
