### ISSUE TITLE
Text failed. "confirmSent" failed.

### ISSUE THREAD

**Issue by fkhachi** [Brismuth-Apps-LLC/bulk-texter-lite#212]
**Describe the bug**
Bulk Texter Lite v2.0.10: Text failed. "confirmSent" failed. 

**URL**
The URL you were on when the problem occurred. 
https://voice.google.com/u/0/messages?itemId=t.%2B19085772529

**Expected behavior**
Getting the same error on both Firefox and Chrome

**Screenshots**

https://www.loom.com/share/17e041bdc6dc44aa9b6e0becd6de3eae

**Additional context**

I have copied the errors log for your review.
Bulk Texter Lite v2.0.10: Text failed. "confirmSent" failed. You can find support resources by opening the Bulk Texter Lite popup and clicking "Get Help" at the bottom. When you click "ok" the page will refresh.
Context
https://voice.google.com/u/0/messages?itemId=draft-7D48D793-83E7-4F49-A0B4-A093ED369AE4
Stack Trace
•	contentScripts/tools.js:40 (fatalErrorHandler)
•	contentScripts/tools.js:65 (keepTrying)
// Microsoft Edge compatibility
if (chrome == null) {
  chrome = browser;
}

/**
 * removes all non-numeric characters from the number string
 * @param  {string}   number i.e. +1 (223) 456-7890
 * @return {string}         i.e. 2234567890
 */
function formatNumber(number) {
  var simplifiedNumber = number.trim().replace(/\D/g,'');
  // remove international code for US numbers
  if (simplifiedNumber.length === 11 && simplifiedNumber.charAt(0) === '1') {
    simplifiedNumber = simplifiedNumber.substr(1);
  }
  return simplifiedNumber;
}

function getFunctionName(func) {
  return func.name.replace(/bound /g, '');
}

/**
 * continually calls the given method until successful
 * Promisified for use with async/await
 * @param {Function}   method         should return true when successful, or false when we should give up early
 * @param {bool}       silenceErrors  true if we should not alert on errors
 * @param {Function}   cb             to be called with the results from method when we're done trying
 */
async function keepTrying(method, silenceErrors) {
  function fatalErrorHandler() {
    if (!silenceErrors) {
      const manifest = chrome.runtime.getManifest();
      const fullMessage = `Bulk Texter Lite v${manifest.version}:\nText failed. "${getFunctionName(method)}" failed.\n\nYou can find support resources by opening the Bulk Texter Lite popup and clicking "Get Help" at the bottom.\n\nWhen you click "ok" the page will refresh.`;
      
      if (siteManager) {
        siteManager.messagesToSend.length = 0;
      }
      console.error(fullMessage);
      alert(fullMessage);
      window.location.reload();
    }
  }

  console.log('BulkTexterLite: Running: ', getFunctionName(method));
  const frequency = 200; // try every 200ms
  let tryCount = 5 * 1000/frequency; // keep trying for 5 seconds
  
  while (tryCount-- > 0) {
    await sleep(frequency);

    let successful = method();
    if (successful === true) {
      return true;
    }

    let giveUp = successful === false;
    if (giveUp) {
      fatalErrorHandler();
      return successful;
    }
  }

  fatalErrorHandler();
  return false;
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

/**
 * Sends a message to background.js for storage (usage tracking for future user-visible dashboards, and anonymous data for developer)
 * @param  {object} payload  value to be logged
 */
function logEvent(payload) {
  chrome.runtime.sendMessage({
    gvbt_logger: true,
    payload: payload
  });
}

/**
 * Removes unicode characters from the text
 */
function removeUnicode(text) {
  return text.replace(/([\u2700-\u27BF]|[\uE000-\uF8FF]|\uD83C[\uDC00-\uDFFF]|\uD83D[\uDC00-\uDFFF]|[\u2011-\u26FF]|\uD83E[\uDD10-\uDDFF])/g, '');
}

/**
 * Removes whitespace from the text
 */
function removeWhitespace(text) {
  return text.replace(/\s/g,'');

}

Bulk Texter Lite v2.0.10: Text failed. "confirmSent" failed. You can find support resources by opening the Bulk Texter Lite popup and clicking "Get Help" at the bottom. When you click "ok" the page will refresh.
Context
https://voice.google.com/u/0/messages?itemId=draft-AFCF6F5A-5C3D-4EE0-A30F-128665A949CB
Stack Trace
•	contentScripts/tools.js:40 (fatalErrorHandler)
•	contentScripts/tools.js:65 (keepTrying)
// Microsoft Edge compatibility
if (chrome == null) {
  chrome = browser;
}

/**
 * removes all non-numeric characters from the number string
 * @param  {string}   number i.e. +1 (223) 456-7890
 * @return {string}         i.e. 2234567890
 */
function formatNumber(number) {
  var simplifiedNumber = number.trim().replace(/\D/g,'');
  // remove international code for US numbers
  if (simplifiedNumber.length === 11 && simplifiedNumber.charAt(0) === '1') {
    simplifiedNumber = simplifiedNumber.substr(1);
  }
  return simplifiedNumber;
}

function getFunctionName(func) {
  return func.name.replace(/bound /g, '');
}

/**
 * continually calls the given method until successful
 * Promisified for use with async/await
 * @param {Function}   method         should return true when successful, or false when we should give up early
 * @param {bool}       silenceErrors  true if we should not alert on errors
 * @param {Function}   cb             to be called with the results from method when we're done trying
 */
async function keepTrying(method, silenceErrors) {
  function fatalErrorHandler() {
    if (!silenceErrors) {
      const manifest = chrome.runtime.getManifest();
      const fullMessage = `Bulk Texter Lite v${manifest.version}:\nText failed. "${getFunctionName(method)}" failed.\n\nYou can find support resources by opening the Bulk Texter Lite popup and clicking "Get Help" at the bottom.\n\nWhen you click "ok" the page will refresh.`;
      
      if (siteManager) {
        siteManager.messagesToSend.length = 0;
      }
      console.error(fullMessage);
      alert(fullMessage);
      window.location.reload();
    }
  }

  console.log('BulkTexterLite: Running: ', getFunctionName(method));
  const frequency = 200; // try every 200ms
  let tryCount = 5 * 1000/frequency; // keep trying for 5 seconds
  
  while (tryCount-- > 0) {
    await sleep(frequency);

    let successful = method();
    if (successful === true) {
      return true;
    }

    let giveUp = successful === false;
    if (giveUp) {
      fatalErrorHandler();
      return successful;
    }
  }

  fatalErrorHandler();
  return false;
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

/**
 * Sends a message to background.js for storage (usage tracking for future user-visible dashboards, and anonymous data for developer)
 * @param  {object} payload  value to be logged
 */
function logEvent(payload) {
  chrome.runtime.sendMessage({
    gvbt_logger: true,
    payload: payload
  });
}

/**
 * Removes unicode characters from the text
 */
function removeUnicode(text) {
  return text.replace(/([\u2700-\u27BF]|[\uE000-\uF8FF]|\uD83C[\uDC00-\uDFFF]|\uD83D[\uDC00-\uDFFF]|[\u2011-\u26FF]|\uD83E[\uDD10-\uDDFF])/g, '');
}

/**
 * Removes whitespace from the text
 */
function removeWhitespace(text) {
  return text.replace(/\s/g,'');

}

**Comment by brismuth** [comment]
See the Support page - the confirmSent error typically means that Google has temporarily blocked your account or rate limited your messages:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/blob/main/support.md#account-suspension--error-confirmsent-failed

Are you able to send the same messages manually, without Bulk Texter Lite? And do those succeed?

**Comment by fkhachi** [comment]
Thank you very much. That's what I suspected as I made the same mistake several years ago and I learned my lesson. It does not allow me to send the same message individually and manually which is rather odd. 

 

How long does it take for them to unblock you?

 

I assume that you are the developer for the software and since I have you on with me, I would be interested to know if the Pro version would resolve this problem or provide me with additional benefits.

 

Fred Khachi

Mobile      (209) 763-8787

**Comment by brismuth** [comment]
The Pro version does have some additional features that can help with this - especially CSV upload - see the full feature breakdown here:
https://www.bulktexterpro.com/docs/features

The Bulk Texter Pro FAQ also has a lot of tips that may be useful to you:
https://www.bulktexterpro.com/docs/faq/#do-you-have-any-tips-to-avoid-having-my-messages-flagged-as-spam

The Pro version also currently offers a 7 day free trial - so I'd say give it a try once your account is working again. :)

**Comment by fkhachi** [comment]
Thank you and have a great new year.

 

Fred Khachi

Mobile      (209) 763-8787
