### ISSUE TITLE
"switchToMessagesTab" failed.

### ISSUE THREAD

**Issue by Rockshort** [Brismuth-Apps-LLC/bulk-texter-lite#213]
**Describe the bug**
Error message: Bulk Texter Lite v2.1.0: Text failed. "switchToMessagesTab" failed.
**URL**
The URL you were on when the problem occurred. 
https://voice.google.com/u/0/messages
**Expected behavior**
I've used the extension before successfully. I tried changing the delay from 15 sec to 30 sec.
**Screenshots**

**Additional context**
<img width="375" alt="Screenshot 2023-01-12 at 9 36 49 PM" src="https://user-images.githubusercontent.com/4294318/212224415-940c3b50-6b26-4632-b254-df9628af23a0.png">

**Comment by brismuth** [comment]
Thanks for the report. Google rolled out some new changes today that caused this issue.

Bulk Texter Lite v2.1.1 is now available in the Firefox add-on store and resolves the problem.

You can follow these steps to force Firefox to update to v2.1.1, if it hasn't already:
1. Go to about:addons in Firefox.
2. Click the Settings icon at the top right of the page.
3. Click "Check for Updates".
4. Click "Update Now".
