### ISSUE TITLE
"switch to messages tab"

### ISSUE THREAD

**Issue by markieSN** [Brismuth-Apps-LLC/bulk-texter-lite#214]
I am trying to launch the mass texter and I receive an error:

"Text failed. 'switchToMessagesTab' failed.

![image](https://user-images.githubusercontent.com/122736411/212548291-0f994355-a783-425c-9e5e-bc1a6032cdcd.png)

**Comment by brismuth** [comment]
This is due to breaking changes Google made to Google Voice - it is fixed in v2.1.1.

See https://github.com/Brismuth-Apps-LLC/bulk-texter-lite#update-it for instructions on updating.
