### ISSUE TITLE
Text Failed "switchToMessagesTab"

### ISSUE THREAD

**Issue by adefilip** [Brismuth-Apps-LLC/bulk-texter-lite#216]
**Describe the bug**
Bulk Texter would not send a message in Chrome. Instead I got the screen shot message below. 

**Expected behavior**
I expected to send a message

**Screenshots**
![image](https://user-images.githubusercontent.com/47867915/212916741-59d2f676-1da9-4902-98a2-60b9c25f499c.png)

**Comment by brismuth** [comment]
Google rolled out some new changes several days ago that caused this issue.

Bulk Texter Lite v2.1.1 is available in the Firefox add-on store and resolves the problem.

See https://github.com/Brismuth-Apps-LLC/bulk-texter-lite#update-it

**Comment by adefilip** [comment]
When will the issues with Chrome be resloved?

**Comment by brismuth** [comment]
Bulk Texter Lite is not on the Chrome web store.

The issues are resolved in version v2.1.1 though, which is open source and posted on here. Based on the screen shot, you are running an old manually installed version of Bulk Texter Lite. 

See https://github.com/Brismuth-Apps-LLC/bulk-texter-lite#update-it

**Comment by adefilip** [comment]
thank you!

**Comment by Anyssa1** [comment]
I am facing the same problem with the version v2.1.1  in the chrome

**Comment by Anyssa1** [comment]
![image](https://user-images.githubusercontent.com/122944132/213038487-6d60037b-95f9-4101-9215-1c7c78a335cd.png)

**Comment by brismuth** [comment]
Hmm. @Anyssa1 that's a different error, and not one that I've seen reported. Could be additional changes from Google though.

Could you take a look at the suggestions on the [support page](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/blob/main/support.md) and open a separate issue if none of the suggestions help?
