### ISSUE TITLE
Write Message Failed

### ISSUE THREAD

**Issue by Anyssa1** [Brismuth-Apps-LLC/bulk-texter-lite#218]
![image](https://user-images.githubusercontent.com/122944132/213942138-9ac63e29-086f-4573-966e-1c4f21f43678.png)

I have updated the latest version but still i find the messages I have automated are not writing in the message box then after sometime this error appears in the screen.

**Comment by brismuth** [comment]
Sorry to hear that - a couple questions:

1. Was it working for you before, or are you trying to get it to work for the first time?
2. Can you confirm that you tried all the tips on the support page? https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/blob/main/support.md#general-tips

**Comment by mr-574rk** [comment]
Same here it doesn't work even with the pro version...

**Comment by brismuth** [comment]
Sounds like Google Voice may be changing their interface in a way that will require Bulk Texter Lite / Pro to be updated.

Just to confirm, it was working for you before, right? And it suddenly stopped working?

Bulk Texter Pro subscribers that are having issues should email support@bulktexterpro.com, we're typically able to get things sorted out pretty quickly and then get the fix ported to Bulk Texter Lite soon after.

**Comment by mr-574rk** [comment]
Yes it was then stopped suddenly

**Comment by brismuth** [comment]
Can you follow these steps in Chrome? That will help me get a fix out.

1. Go to https://voice.google.com/u/0/messages.
2. Click and open any message thread.
3. Right click on the part of the page where you write new text messages, and click "Inspect". It should show something like this:

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/5679695/214613647-d0d1c12d-aeb6-4d61-b4fa-bb1af4a2571f.png">

4. Right click on the highlighted blue code that says `<textarea` or similar, then "Copy", then "outerHTML", and paste the output here, as shown here:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/5679695/214614099-9cf5c297-335c-4bc7-8e56-8ffbbb3e5620.png">

For example, this is what mine outputs:
```html
<textarea aria-label="Type a message" flex="" gv-test-id="gv-message-input" gv-focus-when="ti1" autocomplete="off" md-no-resize="" ng-attr-placeholder="{{ctrl.getPlaceHolderText()}}" ng-class="::ctrl.Css.INPUT" ng-keypress="ctrl.onKeydown($event)" ng-model="ctrl.inputMessage" ng-readonly="ctrl.isSendSmsDisabled()" class="ng-valid md-input gvMessageEntry-input flex ng-touched ng-not-empty ng-dirty ng-valid-parse" id="input_0" rows="1" placeholder="Type a message" aria-invalid="false" style="height: 56px;">      </textarea>
```
