### ISSUE TITLE
Invalid number warning 

### ISSUE THREAD

**Issue by wtibor** [Brismuth-Apps-LLC/bulk-texter-lite#219]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**
Suddenly

**Describe the bug**

I've been using this for months and I'm using the appropriate format for numbers. I've tried uninstalling, reinstalling - nothing works
**Screenshots**
![image](https://user-images.githubusercontent.com/124298870/216412259-6abc21bc-54dc-41aa-a6b5-474c3d8a6c35.png)

**Comment by brismuth** [comment]
@wtibor are those all the numbers that you have inserted? 

The way this error looks, Bulk Texter Lite thinks that you have a line somewhere in the phone number input that has a comma at the front of the line with nothing in front of the comma. I'd say double check all the lines in that input. 

[Bulk Texter Pro](https://www.bulktexterpro.com) also makes it much easier to track down issues with your input.

**Comment by wtibor** [comment]
Yes, they are - this is how I do it every time - but I’ll try that. Thanks for getting back to me;)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
