### ISSUE TITLE
Integrate with Google Contacts

### ISSUE THREAD

**Issue by sjWiz** [Brismuth-Apps-LLC/bulk-texter-lite#22]
Hi,

I am trying to enter names of my contacts (in the numbers, contacts box) but it's not prefilling with existing contacts in my address book like it does in gVoice or gHangouts. I have over 1000 contact names.

Why doesn't the extension recognize the presence of existing contacts?

Thanks,
sJ

**Comment by brismuth** [comment]
Hi, that feature hasn't been built, but I think it's a cool idea. That said, I don't have a lot of spare time right now to build it out and it's not something that I need for my use case.

If you have some experience coding and would like to build it out though, I'd welcome the pull request.

**Comment by sjWiz** [comment]
Thanks Brian for your response. I understand. If you make time to build
this feature in that would be great! :D

**Comment by ScottyGoodBoy** [comment]
> Hi, that feature hasn't been built, but I think it's a cool idea. That said, I don't have a lot of spare time right now to build it out and it's not something that I need for my use case.

I would love that feature but understand your time.  I used your extension yesterday for the first time and loved it.  I gave you a small donation!

**Comment by cubemrl** [comment]
It is a great addon. I love it! 

I do not have experience coding but so understand the basic concepts. If you can direct me with the steps I can give it a try. I would love to contribute to it. I also would like to be able to select the numbers from Google Contacts. 

Thank you.

**Comment by brismuth** [comment]
@cubemrl integrating with Google Contacts would be a good sized amount of work, and there are multiple different ways it could be done. There aren't really simple instructions I can post telling how to do it, or I would.

**Comment by AmeliaPR** [comment]
I need this feature as well. Otherwise the extension will not work for me

**Comment by brismuth** [comment]
People who would like this issue prioritized can fund it here:
https://issuehunt.io/r/brismuth/google-voice-bulk-texter/issues/22

**Comment by cubemrl** [comment]
This is a great idea.

**Comment by CNBarnes** [comment]
Personally, I plan to simply use a google sheets spreadsheet, BUT I can see how integrating this to look at Google Contacts could also be useful.    One thing I would suggest is that IF this is done, that the integration be able to select a particular label within contacts in order to choose a group of people to send a bulk message to (as opposed to everyone in the entire contacts list).

**Comment by brismuth** [comment]
Hey folks - I have an exciting announcement!

I just launched Bulk Texter Pro over at https://www.bulktexterpro.com/ - it supports CSV upload with multiple columns, as well as scheduling messages in advance and message previewing - it's pretty slick.
There is not currently a Google Contacts integration, but it's on the roadmap: https://www.bulktexterpro.com/docs/features/

I'd love if you could check it out and drop any feedback you have here.

**Comment by cubemrl** [comment]
Thank you Brian,

Any cost associated with this?

Thank you again.

**Comment by brismuth** [comment]
Yes - $14.95 a month. However, there is a free 7-day trial, and I will also continue supporting the completely free Google Voice Bulk Texter here with all the features it currently has.

You can see more on the FAQ here:
https://www.bulktexterpro.com/docs/faq
