### ISSUE TITLE
This does not work

### ISSUE THREAD

**Issue by Mathmom11** [Brismuth-Apps-LLC/bulk-texter-lite#222]
I try to send a simple text to my own phone.
Goes to pending
I try to upload CSV to send immediately
Goes to pending
I try to put in numbers to send later
Goes to pending.
Nothing works.
I am frustrated, and I am about to cancel.
Please someone reach out to me to resolve this issue

**Comment by brismuth** [comment]
Hi @Mathmom11! Sorry to hear that, that sounds really frustrating.

It sounds like you're asking about Bulk Texter Pro. 
As a Bulk Texter Pro subscriber, you're eligible for personal support by emailing support@bulktexterpro.com - this page is for the free community/forum support for Bulk Texter Lite.

I'd recommend taking a look at the troubleshooting guide, and if you're still having issues, sending an email over to support@bulktexterpro.com.
https://www.bulktexterpro.com/docs/troubleshooting-guide#2---i-can-click-sendschedule-but-my-messages-stay-in-pending-and-nothing-happens

**Comment by Mathmom11** [comment]
I need a number to call. I wrote them already. I went through the trouble shooting guide.

**Comment by brismuth** [comment]
Thanks for reaching out to support, we'll work with you via phone/email.
