### ISSUE TITLE
After latest google update   Error Confirm Send failed. 

### ISSUE THREAD

**Issue by elmar1** [Brismuth-Apps-LLC/bulk-texter-lite#223]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**
Seems to have started on Chrome update. 
**Describe the bug**
Does not go through the list, hangs after the top one gets stuck then error message refreshing the page then go into app and delete top entry and it will send the next one.   Screen shot attached.  Still a great time saver Thanks, 

**Screenshots**

![Error confirm send failed GV Bulk Texter](https://user-images.githubusercontent.com/1020611/226072312-2695d1ac-2312-4e0d-a62e-b86742d8faf1.jpg)

**Comment by brismuth** [comment]
Hi @elmar1, thanks for reporting the issue. Bulk Texter Lite seems to be working fine for me on the latest version of Chrome.

However, it looks like you're using v1.3.2, which is a very old version of Bulk Texter Lite. Can you try upgrading following these instructions and see if you're still seeing the issue?

https://github.com/Brismuth-Apps-LLC/bulk-texter-lite#update-it

**Comment by elmar1** [comment]
Thanks for your reply. updated in Chrome by reinstalling with newest version. 
Perfect!
I feel kind of leary about logging in to google voice on edge thus my chrome habit. 
Cheers!
Elmar Vaher
Get BlueMail <https://bluemail.me> for Desktop
Brian Smith wrote:
Hi @elmar1 <https://github.com/elmar1> , thanks for reporting the issue. Bulk Texter Lite seems to be working fine for me on the latest version of Chrome.
However, it looks like you're using v1.3.2, which is a very old version of Bulk Texter Lite. Can you try upgrading following these instructions and see if you're still seeing the issue?
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite#update-it <https://github.com/Brismuth-Apps-LLC/bulk-texter-lite#update-it>
