### ISSUE TITLE
Some iphone users not receiving messages

### ISSUE THREAD

**Issue by dovnew** [Brismuth-Apps-LLC/bulk-texter-lite#225]
This issue has been happening for awhile.

I send out daily messages to about 10-15 users. In google voice all messages are being shown as sent. Several users are however not receiving the messages. However if I send these same users messages directly from google voice as a single message (without using bulk texter) then they receive the message.

It seems that this is only happening to users with iphones,

Thank you

**Comment by brismuth** [comment]
Hi @dovnew, unfortunately that would be entirely on the Google Voice side of things. If Google Voice says that the messages are being sent, then Bulk Texter Lite trusts that, and has no additional special means to verify that they were.

Thanks,
