### ISSUE TITLE
not sending and no error on the page - only in the extensions area of chrome

### ISSUE THREAD

**Issue by wendihenry** [Brismuth-Apps-LLC/bulk-texter-lite#226]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**

**Describe the bug**

**Screenshots**
<img width="675" alt="Screenshot 2023-04-28 at 8 46 53 AM" src="https://user-images.githubusercontent.com/132080708/235180654-a83f0770-22c1-48f0-aa1c-1e3c279022ce.png">
<img width="667" alt="Screenshot 2023-04-28 at 8 46 45 AM" src="https://user-images.githubusercontent.com/132080708/235180663-dab46580-623b-4a3e-8ab6-597b6d1b04b0.png">

**Comment by brismuth** [comment]
Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?

And can you confirm that you are using Google Voice in English, per the support guide?
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/blob/main/support.md
> Although text messages can be in any language, Bulk Texter Lite requires that the Google Voice interface be in English - make sure that both your Google Account and your browser settings are set to English for the Google Voice page.

**Comment by JessC-Tech24** [comment]
Hi, I am also having this issue, I didn't use the extension for about 3 months. I went to use it today and got the  same issue as above.  I am using Voice in English. 
![Untitled-1](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/134640914/d3ba9d6e-c209-4fea-af63-a76e0e8abff5)
