### ISSUE TITLE
Hi, I love the app and has worked great before

### ISSUE THREAD

**Issue by johanxaguirre** [Brismuth-Apps-LLC/bulk-texter-lite#227]
Recently, I have been attempting to group text again but for some reason, I can only send out to one phone # and then it fails after that. 

I have the correct formats as I did before but now it's not working.

Any help is much appreciated.

Best

**Comment by brismuth** [comment]
Are your referring to Bulk Texter Lite or Bulk Texter Pro? Bulk Texter Lite does not support group texting (multiple phone numbers per message), while Bulk Texter Pro does.

If you are using Bulk Texter Lite, it would be helpful to provide any additional details you can, after reviewing the support page here:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/blob/main/support.md
