### ISSUE TITLE
Unable to Update or Use Extension

### ISSUE THREAD

**Issue by ktuckmacalla** [Brismuth-Apps-LLC/bulk-texter-lite#229]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**
I have used Bulk Texter Lite for months

**Describe the bug**
My version is not up to date. But I am not able to update it in the store. When I try to use it, it doesn't recognize the google voice page.

**Screenshots**

**Comment by brismuth** [comment]
What version are you on, and what browser are you using?

**Comment by ktuckmacalla** [comment]
I was on 2.0.5. I am using google chrome 114.0.5735.110Sent from my iPhoneOn Jun 6, 2023, at 1:27 PM, Brian Smith ***@***.***> wrote:﻿
What version are you on, and what browser are you using?

**Comment by ktuckmacalla** [comment]
This is what the errors look like Sent from my iPhoneOn Jun 6, 2023, at 1:27 PM, Brian Smith ***@***.***> wrote:﻿
What version are you on, and what browser are you using?

**Comment by brismuth** [comment]
Sorry, if you sent a screenshot, it didn’t come through. No worries though, it sounds like the issue is almost certainly caused by running an old version. 

What happens when you follow the Update instructions here?
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite#update-it
