### ISSUE TITLE
Bulk Texter Lite v2.1.4: Text failed. "fillNumberInput" failed.

### ISSUE THREAD

**Issue by WhiteOlive2020** [Brismuth-Apps-LLC/bulk-texter-lite#230]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**

**Describe the bug**

**Screenshots**

**Comment by WhiteOlive2020** [comment]
![Screenshot 2023-06-29 121321](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/110500749/f9cabb67-8319-4cec-bcac-3edabc951966)

**Comment by brismuth** [comment]
Hi @WhiteOlive2020, is this happening with all phone numbers or only with some phone numbers? Is it happening on every text you try to send?

**Comment by WhiteOlive2020** [comment]
its will send like 3 texts and then stop. I am sending one a minute
