### ISSUE TITLE
not sending messages

### ISSUE THREAD

**Issue by mrsarentoft** [Brismuth-Apps-LLC/bulk-texter-lite#231]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**
I've been using the extension regularly for several years. It was working until 8/10/23 then started glitching on 8/11/23. I waited until today to try again. Same results.

**Describe the bug**
I am able to send regular messages using Google Voice but the bulk text messages aren't going through. I don't get an error message. I can see the phone number and message appear but nothing goes through. I was sending 1 minute apart and only about 5-10 messages. I tried in both Firefox and Edge.

**Screenshots**

**Comment by brismuth** [comment]
Thanks for the details. It sounds like you were very thorough in troubleshooting this.

My guess is that Google has made some changes to their interface and have rolled them out to your account, but not to everyone's. If that's the case, Bulk Texter Lite will need to be updated to support the new changes.

Would you be willing to email us at support@bulktexterpro.com to coordinate a zoom call to troubleshoot?

**Comment by mrsarentoft** [comment]
Yes, I would be happy to assist. Your extension is a lifesaver for me. I do want to make one more attempt from home tonight to rule out an issue with my firewall. (I work for a school district but my school Google account doesn’t support Google Voice.)Sent from my iPhoneOn Aug 14, 2023, at 2:13 PM, Brian Smith ***@***.***> wrote:﻿
Thanks for the details. It sounds like you were very thorough in troubleshooting this.
My guess is that Google has made some changes to their interface and have rolled them out to your account, but not to everyone's. If that's the case, Bulk Texter Lite will need to be updated to support the new changes.
Would you be willing to email us at ***@***.*** to coordinate a zoom call to troubleshoot?
