### ISSUE TITLE
Can't run lite version after installing pro on Firefox

### ISSUE THREAD

**Issue by DWTSD** [Brismuth-Apps-LLC/bulk-texter-lite#233]
Hello,
I installed the pro version in Firefox 120.0  It prompted me for my email and I entered it and confirmed it with the emailed confirmation code.  
I un-installed pro, and then installed lite.  It shows it is installed, but don't know how to launch it.

**Comment by brismuth** [comment]
Installing or uninstalling the Pro version would not have any impact on the Lite version at all.

To use the Lite version, you simply need to click the Bulk Texter Lite icon while on the Google Voice page in your browser, and follow the instructions in the popup. If you don't see the Bulk Texter Lite icon at the top of your browser, you can click the puzzle piece icon at the top right of the browser, then click the Bulk Texter Lite icon in the dropdown.
