### ISSUE TITLE
Messages not sending

### ISSUE THREAD

**Issue by tophermoon** [Brismuth-Apps-LLC/bulk-texter-lite#234]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**
Ive been using Bulk Texter for a few years. This is the first time it has happened.

**Describe the bug**
It is going through the motions of sending the message, but nothing is sent. Then it moves onto the next number and does the same and keeps moving down the list going through the automation, but not actually sending anything.

**Screenshots**
I cant send a picture of no messages being sent. It did pop up with an error code saying it could not send a message, but it went away so fast I couldn't read it. I cant get it to recreate the error code. My numbers and names are formatted correctly: (XXX) XXX-XXXX, NAME. I send messages about once or twice a week to a list that is smaller that 50 numbers and I have it set to every 30 seconds. Im a teacher and use this for students and also volunteer work at my church. I don't think it would be considered high volume.

**Comment by tophermoon** [comment]
Ive also tried uninstalling it and reinstalling it from firefox.

**Comment by tophermoon** [comment]
Now I can text me personal cell number, but still no other numbers. My cell number is associated with the google voice account. I tried accessing the account in a privet window in firefox, nothing looked different.

**Comment by brismuth** [comment]
Are you using Bulk Texter Pro or Bulk Texter Lite? Typically Bulk Texter Lite should halt texting if any issues occure.

Are you able to send the same exact texts manually, without Bulk Texter Lite? If not, that would indicate that Google Voice is blocking the texts, rather than there being an issue with Bulk Texter Lite. See this entry in the support guide:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/blob/main/support.md#some-messages-arent-sending-but-others-are-im-not-getting-any-error-messages

**Comment by tophermoon** [comment]
Ok, Sounds like my number got shut down? Im using the lite version. It just keeps going and not sending messages. I tried again this morning and got a message saying the message was not sent and was referred to this link:

https://support.google.com/voice/answer/9230450

Im not sure what to have done differently. Could someone have marked the number or message as spem and then it triggered this?

**Comment by tophermoon** [comment]
It seems like I can message people, just not with plug in. Its like its sensing when Im using it.

**Comment by brismuth** [comment]
If you are able to send texts manually, without Bulk Texter Lite, that would indicate an issue with Bulk Texter Lite, rather than an issue with your account being blocked.

Is Bulk Texter Lite having issues putting in phone numbers? If so, then this issue is likely the same as #236.

**Comment by tophermoon** [comment]
It is accurately putting in the phone number and the message then acts as if it sent it and moves onto the next number and name on the list. The messages never sent. what information can I send you to troubleshoot this?ChrisSent from my iPhoneOn Dec 15, 2023, at 1:31 PM, Brian Smith ***@***.***> wrote:﻿
If you are able to send texts manually, without Bulk Texter Lite, that would indicate an issue with Bulk Texter Lite, rather than an issue with your account being blocked.
Is Bulk Texter Lite having issues putting in phone numbers? If so, then this issue is likely the same as #236.

**Comment by brismuth** [comment]
This sounds like a different issue than #236 and #237, but in case it's related, I'd recommend updating to v3.0.2 and seeing if that helps with the issue.

You can follow the instructions here to update to the latest version:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite?tab=readme-ov-file#update-it
