### ISSUE TITLE
Piping two names

### ISSUE THREAD

**Issue by gmaramag** [Brismuth-Apps-LLC/bulk-texter-lite#235]
Hi Brian,

First of all, love this extension. Thanks so much for creating it. You've saved a couple of years of my life from soulless mass-texting.

Just curious: would it be possible to pipe a {name_1} and {name_2} into the same message? This is helpful for super personalized messages and would extend my life even more. Hope that isn't too greedy!

Thank you! 😄

**Comment by brismuth** [comment]
Hi Gabrielle!

I recommend checking out Bulk Texter Pro. It supports what you’re describing via [CSV Upload](https://www.bulktexterpro.com/docs/getting-started/using-csv-upload/), as well as many additional features! It’s where I’m focusing all active development efforts currently. 
https://www.bulktexterpro.com/

Thanks!
