### ISSUE TITLE
Scheduled texts (on Bulk Texter Pro) allows for date/time in the past

### ISSUE THREAD

**Issue by stacksjb** [Brismuth-Apps-LLC/bulk-texter-lite#239]
When scheduling a message to send, Bulk Texter Pro allows you to select a date/time in the past; it should not let you do that.

To further improve the feature, two requests would be:
1) It would be great if the date/time was a bit clearer - adding the timezone (I assume, but it isn't clear, that it is local?
2) Adding a calculated "In <x> days" (or hours/minutes etc) would also make that clear.

**Comment by brismuth** [comment]
Thanks for the feedback!

1. Yes, it's in your local time zone.
2. That's a great idea, I've added that to the backlog and will post back on this thread when it's done.

Also, as an FYI, Bulk Texter Pro subscribers can email us at support@bulktexterpro.com to request support directly.

**Comment by stacksjb** [comment]
Related - I found that if your computer or browser is offline, the messages will be missed. I should have hte option to re-send if desired.

**Comment by brismuth** [comment]
That is correct, the computer needs to be on and unlocked for Bulk Texter Pro to send texts, per the FAQ:
https://www.bulktexterpro.com/docs/faq/#will-bulk-texter-pro-still-send-texts-if-my-computer-is-asleep--locked--hibernating--turned-off

Bulk Texter Pro supports re-sending texts via the History tab, see this article:
https://www.bulktexterpro.com/docs/getting-started/resending-messages/

**Comment by AlxndrCtamn** [comment]
Hi @brismuth We currently have an issue with Google Voice, as it automatically stops when texting.

**Comment by brismuth** [comment]
@AlxndrCtamn if this is about Bulk Texter Lite, please submit a new issue with more detail describing the problem. If this is about Bulk Texter Pro, please email support@bulktexterpro.com with more detail.

**Comment by brismuth** [comment]
@stacksjb, v2.7.5 is queued up for release on the web stores, and includes changes to address your feedback on this thread! Thanks again for sharing the feedback!
