### ISSUE TITLE
Keep getting Invalid phone number: error.

### ISSUE THREAD

**Issue by 3786matt** [Brismuth-Apps-LLC/bulk-texter-lite#242]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**
I use bulk texter light frequently and this issue just began. 

**Describe the bug**
When I send a message using my usual list of contacts, I get the "Invalid phone number:" error. I use this list weekly and have never had this issue. I've gone through the list and don't see any formatting errors on my end. I did notice that Edge updated overnight, however. I included a screen shot of the error, but removed the message/contacts for privacy reasons. Thanks very much.

**Screenshots**
![image](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/18645237/cd8d0d66-ed0b-4b55-94fd-e6a993d76574)

**Comment by brismuth** [comment]
Do you maybe have a bunch of empty lines in the "Number, names" input? It should probably just ignore empty lines, but it doesn't currently, and instead assumes that every line should have a valid number.

**Comment by 3786matt** [comment]
There were some empty lines at the end. I eliminated those and now google voice says “No contacts found” when I send through Bulk Texter. If I send texts individually using google voice itself, it works. I’ve tried closing out the window and opening a new one. Thanks very much for your help. Sent from Mail for Windows From: Brian SmithSent: Thursday, February 29, 2024 5:53 PMTo: Brismuth-Apps-LLC/bulk-texter-liteCc: 3786matt; AuthorSubject: Re: [Brismuth-Apps-LLC/bulk-texter-lite] Keep getting Invalid phone number: error. (Issue #242) Do you maybe have a bunch of empty lines in the "Number, names" input? It should probably just ignore empty lines, but it doesn't currently, and instead assumes that every line should have a valid number.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by brismuth** [comment]
So at this point, is Bulk Texter Lite working for you? If not, I'd recommend clearing out the "Numbers, Names" input entirely, if you haven't already, and starting clean there. 

And then, if you're getting a different error now, if you could share a screenshot of it on the Github thread that would be great.
