### ISSUE TITLE
ConfirmSent error incorrectly displaying with Bulk Texter Pro v.2.6.0

### ISSUE THREAD

**Issue by untalkatively** [Brismuth-Apps-LLC/bulk-texter-lite#243]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**
I am new to both the Pro and Lite versions. 

**Describe the bug**
When I tested the product by sending the text to my cell phone directly and to Google Voice, the messages went through. However, I got the error message.

The 
ConfirmSent error
message is displayed, but the texts were successfully sent. This is in Google Voice in Edge.
**Screenshots**
![image](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/161361310/752ea953-dcb3-4333-995f-144767a245ab)

**Comment by brismuth** [comment]
Hi @untalkatively, can you email support@bulktexterpro.com? If the message is being sent but Bulk Texter Pro thinks it failed, we will probably need to get on a zoom call to resolve that.
