### ISSUE TITLE
Error Message: "Message not delivered. See acceptable use policy"

### ISSUE THREAD

**Issue by kussin27** [Brismuth-Apps-LLC/bulk-texter-lite#247]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**
This is my first time using Bulk Texter Lite

**Describe the bug**
After successfully sending around 85 messages this error happened when I tried to send an individual text outside of the script. Seems like maybe my account was flagged from how Bulk Texter Lite was sending throughout the day?

**Screenshots**

**Comment by brismuth** [comment]
See our support page:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/blob/main/support.md#general-tips

> If you are unable to send a message manually (without Bulk Texter Lite), then that is an issue with your Google Voice account or the number you're sending to, and is not an issue that Bulk Texter Lite can help with. If Bulk Texter Lite isn't working, try sending a message manually and see if that works.

> **Some messages aren't sending, but others are. I'm not getting any error messages.**
> If Bulk Texter Lite worked for you for one or more messages but not for others, it is likely that Google is rate limiting you.
> We can not comment on Google Voice's limits, as they are not published, and Bulk Texter Lite is not affiliated with Google/Google Voice.
> You can find tips and best practices in the Bulk Texter Pro [FAQ](https://www.bulktexterpro.com/docs/faq/#what-are-the-recommended-best-practices-for-using-bulk-texter-pro) that may help you avoid being rate limited or blocked by Google: https://www.bulktexterpro.com/docs/faq/#what-are-the-recommended-best-practices-for-using-bulk-texter-pro
