### ISSUE TITLE
Can't install it on Chrome

### ISSUE THREAD

**Issue by DLM1166** [Brismuth-Apps-LLC/bulk-texter-lite#249]
I am choosing the correct folder but still receive the 'missing manifest' error.

**Comment by brismuth** [comment]
Make sure you're downloading the right file – it's at this link:
https://www.bulktexterpro.com/releases/bulk-texter-lite-chrome.zip

See the instructions here:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite?tab=readme-ov-file#installing-bulk-texter-lite

As long as you're following the instructions exactly, it should work.

**Comment by DLM1166** [comment]
Thank you! That file worked. The one I downloaded from github didn't.
