### ISSUE TITLE
Looping on a single number then erroring out

### ISSUE THREAD

**Issue by nben71** [Brismuth-Apps-LLC/bulk-texter-lite#250]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**

This has happened before, but clicking in the past after receiving an error message as resolved the issue.  

**Describe the bug**

As of today, it loops 5x on the same number then error's out, nothing sends.

**Screenshots**

<img width="388" alt="Screenshot 2024-06-03 at 2 45 06 PM" src="https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/171615101/5752059c-8769-42e6-b5e7-1544808a2465">

**Comment by brismuth** [comment]
Sorry to hear about the issue.

If you try a simple "hello" message in Bulk Texter Lite, to only your own phone number, do you get the same error message? Or are you only seeing that error message with certain inputs in the "Message" and "Numbers, names" fields?

**Comment by nben71** [comment]
When tried that to two phone numbers, (including myself) it worked with two numbers. Nicole BenwickOn Jun 3, 2024, at 3:50 PM, Brian Smith ***@***.***> wrote:﻿
Sorry to hear about the issue.
If you try a simple "hello" message in Bulk Texter Lite, to only your own phone number, do you get the same error message? Or are you only seeing that error message with certain inputs in the "Message" and "Numbers, names" fields?

**Comment by brismuth** [comment]
Okay, glad to hear that. In that case, it's possible that there's an edge case here where Bulk Texter Lite thinks the message is empty or invalid, or something like that. 

Are you able to consistently reproduce the issue? And if so, any chance you could share exact steps to reproduce the issue? That way I can update Bulk Texter Lite to handle whatever is going on here.

**Comment by nben71** [comment]
I just tried it on a test with three phone numbers and it worked so I went ahead and tried it all and it worked so for now I guess we’re OK. Thank you so much for all of your prompt help. I really appreciate it!!!Nicole BenwickOn Jun 3, 2024, at 4:21 PM, Brian Smith ***@***.***> wrote:﻿
Okay, glad to hear that. In that case, it's possible that there's an edge case here where Bulk Texter Lite thinks the message is empty or invalid, or something like that.
Are you able to consistently reproduce the issue? And if so, any chance you could share exact steps to reproduce the issue? That way I can update Bulk Texter Lite to handle whatever is going on here.

**Comment by brismuth** [comment]
Okay – glad that's working for you now!
