### ISSUE TITLE
Bulk texter not working, but regular texting is working fine.

### ISSUE THREAD

**Issue by tophermoon** [Brismuth-Apps-LLC/bulk-texter-lite#251]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**
I have been using bulk texter for a few years. I just paid the $10 for life price. 

**Describe the bug**
It was working fine, but suddenly messages will not go through when using bulk texter. I can still text people individually and receive texts just fine. 

**Screenshots**
I can not make a screen shot of this happening.

**Comment by tophermoon** [comment]
Its almost as if google can tell that bulk texter is being used and blocking it, but not regular 1:1 texts.

**Comment by brismuth** [comment]
Hi @tophermoon, are you able to consistently reproduce the issue? Typically, if a message fails to go through with Bulk Texter Lite, if you try to send the exact same message to the exact same recipient manually, that will fail too. Messages to other recipients, or messages with different content, may succeed though. 

See our recommended best practices here:
https://www.bulktexterpro.com/docs/faq/#what-are-the-recommended-best-practices-for-using-bulk-texter-pro
