### ISSUE TITLE
src folder deleted

### ISSUE THREAD

**Issue by Geremia** [Brismuth-Apps-LLC/bulk-texter-lite#252]
On commit c393ce3e you comment "Moving source code"; however, it's completely deleted.
Is this project no longer open source? It was MIT-licensed before 2023-12-19.

**Comment by brismuth** [comment]
Hi @Geremia, Bulk Texter Lite is no longer open source. You can read more about the reasoning behind the change here:
https://www.bulktexterpro.com/docs/faq/#why-does-bulk-texter-lite-require-email-registration

**Comment by Geremia** [comment]
@brismuth But isn't the source code in the `.xpi` file anyways?

**Comment by brismuth** [comment]
@Geremia in an attempt to discourage people from using Bulk Texter Lite to abuse the Google Voice platform, the project is no longer open source, and any efforts to reverse engineer or modify the extension are a violation of the terms of use:
https://www.bulktexterpro.com/docs/terms/terms-of-use/#software-usage-restrictions
