### ISSUE TITLE
Google Voice Bulk Texter embedded in Gmail right panel as an Add-on

### ISSUE THREAD

**Issue by EdWood110** [Brismuth-Apps-LLC/bulk-texter-lite#64]
![Bulk Texter Add-On](https://user-images.githubusercontent.com/49246515/58647956-9d965c80-82d6-11e9-8f9e-ef0604b0c777.jpg)
Hi Brian,

We love your app but we have a suggestion. Maybe you could make it so that we could add your Bulk texter to be on the right panel within Gmail, as an add-on? 

This would cut down a lot of forth and back between tabs on our part.

Let me know what you think.

Thank you!

**Comment by brismuth** [comment]
Interesting idea. Are you suggesting putting it there but still having it control Google Voice in a different tab?

**Comment by EdWood110** [comment]
Yes, that would be nice. For example we could stay in our sheet, copying the numbers and messages into the bulk text app, that would streamline the process. No matter what sheet you are on you can use it and send the messages.
For example, when we open the bulk text app and leave the tab to copy another number from another tab, the bulk text app is closed when coming back to that specific tab. We need to click it again to open up and to add a second number for example. 

Having this side app in Chrome would help streamlining the process immensely.

**Comment by brismuth** [comment]
I'm not opposed to that kind of integration, but it would require significant restructuring of the code layout of the extension to run in the page instead of in the pop-up. I'll leave this as an open feature request but I probably won't get to it any time soon. Thanks for the suggestion.

**Comment by methylminer** [comment]
Download autohotkey, and use the "Always on top" script 
Open new window with hangouts/voice
Press Crtl-Space,
Open Bulk Texter
Go back to gmail and copy what you need

Script:

****^SPACE::  Winset, Alwaysontop, , A****

https://www.howtogeek.com/howto/13784/keep-a-window-on-top-with-a-handy-autohotkey-script/

**Comment by brismuth** [comment]
People who would like this issue prioritized can fund it here:
https://issuehunt.io/r/brismuth/google-voice-bulk-texter/issues/64
