### ISSUE TITLE
Add support for Message Presets

### ISSUE THREAD

**Issue by EdWood110** [Brismuth-Apps-LLC/bulk-texter-lite#66]
Hi Brian,

Would it be possible to also save presets of messages and be able so save them within the bulk text app?

So when you have a text campaign you simply enter the numbers and select the right pre-defined message before sending.

Similar to Gmails canned responses, let me know what you think.

**Comment by brismuth** [comment]
Yes, I think this idea makes sense, and could probably be implemented in a bare-bones way without a ton of effort. 

I'm not sure when I'll be able to get to it but when I do I'll update on the thread.

**Comment by brismuth** [comment]
People who would like this issue prioritized can fund it here:
https://issuehunt.io/r/brismuth/google-voice-bulk-texter/issues/66

**Comment by brismuth** [comment]
Hey folks - I have an exciting announcement!

I just launched Bulk Texter Pro over at https://www.bulktexterpro.com/ - it supports CSV upload with multiple columns, as well as scheduling messages in advance and message previewing - it's pretty slick. 
Message presets are not currently supported, but it's on the roadmap: https://www.bulktexterpro.com/docs/features/

I'd love if you could check it out and drop any feedback you have here.
